

from django.urls import path

from DoctorBooking import views

urlpatterns = [
    path('',views.login,name ="login"),
    path('admin_view',views.admin_view, name = "admin_view"),
    path('logincode',views.logincode, name = "logincode"),
    path('new_registrationDoctor',views.new_registrationDoctor, name = "new_registrationDoctor"),
    path('doc_registrationCode',views.doc_registrationCode, name = "doc_registrationCode"),
    path('new_registrationUser',views.new_registrationUser, name = "new_registrationUser"),
    path('user_registrationCode',views.user_registrationCode, name = "user_registrationCode"),
    path('admin_view_doctors',views.admin_view_doctors, name = "admin_view_doctors"),
    path('admin_acceptDoctor/<int:lid>',views.admin_acceptDoctor, name = "admin_acceptDoctor"),
    path('doctor_homePage',views.doctor_homePage, name = "doctor_homePage"),
    path('admin_scheduleView',views.admin_scheduleView, name = "admin_scheduleView"),
    # path('admin_doctorsBooking',views.admin_doctorsBooking, name = "admin_doctorsBooking"),
    path('admin_manageNotifictaion',views.admin_manageNotifictaion, name = "admin_manageNotifictaion"),
    path('admin_viewRatings',views.admin_viewRatings, name = "admin_viewRatings"),
    path('admin_view_users',views.admin_view_users, name = "admin_view_users"),
    path('admin_acceptUser/<int:lid>', views.admin_acceptUser, name="admin_acceptUser"),
    path('admin_rejectUser/<int:lid>', views.admin_rejectUser, name="admin_rejectUser"),
    path('admin_rejectDoctor/<int:lid>', views.admin_rejectDoctor, name="admin_rejectDoctor"),
    path('admin_addNotification', views.admin_addNotification, name="admin_addNotification"),
    path('doctor_viewProfile', views.doctor_viewProfile, name="doctor_viewProfile"),
    path('doctor_manageSchedules', views.doctor_manageSchedules, name="doctor_manageSchedules"),
    path('doctor_addNewSchedule', views.doctor_addNewSchedule, name="doctor_addNewSchedule"),
    path('doctor_viewBooking', views.doctor_viewBooking, name="doctor_viewBooking"),
    path('doctor_viewRating', views.doctor_viewRating, name="doctor_viewRating"),
    path('doctor_changePassword', views.doctor_changePassword, name="doctor_changePassword"),
    path('user_homePage', views.user_homePage, name="user_homePage"),
    path('doctor_editDetails/<int:id>', views.doctor_editDetails, name="doctor_editDetails"),
    path('doctor_editDetailsCode', views.doctor_editDetailsCode, name="doctor_editDetailsCode"),
    path('doctor_addNewScheduleCode', views.doctor_addNewScheduleCode, name="doctor_addNewScheduleCode"),
    path('doctor_scheduleSearch', views.doctor_scheduleSearch, name="doctor_scheduleSearch"),
    path('admin_searchDoctor', views.admin_searchDoctor, name="admin_searchDoctor"),
    path('admin_searchUser', views.admin_searchUser, name="admin_searchUser"),
    path('admin_scheduleView/<int:id>', views.admin_scheduleView, name="admin_scheduleView"),
    path('admin_addNotification', views.admin_addNotification, name="admin_addNotification"),
    path('admin_addNotificationpost', views.admin_addNotificationpost, name="admin_addNotificationpost"),
    path('admin_deleteNotification/<int:id>', views.admin_deleteNotification, name="admin_deleteNotification"),
    path('doctor_viewNotifications', views.doctor_viewNotifications, name="doctor_viewNotifications"),
    path('doctor_changePasswordCode', views.doctor_changePasswordCode, name="doctor_changePasswordCode"),
    path('user_changePasswordCode', views.user_changePasswordCode, name="user_changePasswordCode"),
    path('user_changePassword', views.user_changePassword, name="user_changePassword"),
    path('user_viewProfile', views.user_viewProfile, name="user_viewProfile"),
    path('user_editDetails/<int:id>', views.user_editDetails, name="user_editDetails"),
    path('user_editDetailsCode', views.user_editDetailsCode, name="user_editDetailsCode"),
    path('user_viewDoctor', views.user_viewDoctor, name="user_viewDoctor"),
    path('user_bookDoctor/<int:id>', views.user_bookDoctor, name="user_bookDoctor"),
    path('user_viewAndRemoveBooking', views.user_viewAndRemoveBooking, name="user_viewAndRemoveBooking"),
    path('user_booking', views.user_booking, name="user_booking"),
    path('user_viewPrescription', views.user_viewPrescription, name="user_viewPrescription"),
    path('user_addRating', views.user_addRating, name="user_addRating"),
    path('user_searchDoctor', views.user_searchDoctor, name="user_searchDoctor"),
    path('admin_ViewBookings', views.admin_ViewBookings, name="admin_ViewBookings"),
    path('admin_viewAllBooking/<docid>', views.admin_viewAllBooking, name="admin_viewAllBooking"),
    path('user_booking/<int:id>', views.user_booking, name="user_booking"),
    path('user_searchDoctor2', views.user_searchDoctor2, name="user_searchDoctor2"),
    path('user_deleteSchedule/<int:id>', views.user_deleteSchedule, name="user_deleteSchedule"),
    path('admin_searchDoctor1', views.admin_searchDoctor1, name="admin_searchDoctor1"),
    # path('user_sendRating', views.user_sendRating, name="user_sendRating"),
    path('doctor_searchByDate', views.doctor_searchByDate, name="doctor_searchByDate"),
    path('doctor_viewBookingDeatils/<int:id>', views.doctor_viewBookingDeatils, name="doctor_viewBookingDeatils"),
    path('doctor_uploadPrescriptionCode', views.doctor_uploadPrescriptionCode, name="doctor_uploadPrescriptionCode"),
    path('user_sendRating', views.user_sendRating, name="user_sendRating"),
    path('doctor_uploadPrescription/<int:id>', views.doctor_uploadPrescription, name="doctor_uploadPrescription"),
    path('doctor_viewLastFindings/<int:id>', views.doctor_viewLastFindings, name="doctor_viewLastFindings"),
    path('doctor_editDetails1', views.doctor_editDetails1, name="doctor_editDetails1"),
    # path('admin_viewAllBooking1', views.admin_viewAllBooking1, name="admin_viewAllBooking1"),
    path('user_editDetails1', views.user_editDetails1, name="user_editDetails1"),
    path('logout', views.logout, name="logout"),
    path('flut_login', views.flut_login, name="flut_login"),
    path('flut_register', views.flut_register, name="flut_register"),
    path('flut_userProfile', views.flut_userProfile, name="flut_userProfile"),
    path('flut_viewDoctors', views.flut_viewDoctors, name="flut_viewDoctors"),
    path('flut_bookDoctor', views.flut_bookDoctor, name="flut_bookDoctor"),
    path('flut_bookingDoctor', views.flut_bookingDoctor, name="flut_bookingDoctor"),
    # path('get_doctors', views.get_doctors, name="get_doctors"),
    # path('flut_userAddRating', views.flut_userAddRating, name="flut_userAddRating"),
    path('flut_viewBooking', views.flut_viewBooking, name="flut_viewBooking"),
    path('flut_deleteBooking', views.flut_deleteBooking, name="flut_deleteBooking"),
    path('flut_viewPrescription', views.flut_viewPrescription, name="flut_viewPrescription"),
    path('flut_sendRating', views.flut_sendRating, name="flut_sendRating"),
    path('flut_changePassword', views.flut_changePassword, name="flut_changePassword"),
    path('flut_detailedPrescription', views.flut_detailedPrescription, name="flut_detailedPrescription"),
    path('flut_searchDoctors', views.flut_searchDoctors, name="flut_searchDoctors"),
    path('admin_SearchScheduleByDate', views.admin_SearchScheduleByDate, name="flut_searchDoctors"),
    path('admin_notiSearchDate', views.admin_notiSearchDate, name="admin_notiSearchDate"),
    path('doc_deleteSchedules/<int:id>', views.doc_deleteSchedules, name="doc_deleteSchedules"),
    path('doctor_notiSearchByDate', views.doctor_notiSearchByDate, name="doctor_notiSearchByDate"),




]
