# Generated by Django 5.0.6 on 2024-07-14 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='doctor_reg_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('Designation', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=115)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorBooking.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='prescription_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('notes', models.CharField(max_length=20)),
                ('BOOKING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorBooking.booking_table')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorBooking.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fromtime', models.CharField(max_length=100)),
                ('totime', models.CharField(max_length=100)),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorBooking.doctor_reg_table')),
            ],
        ),
        migrations.AddField(
            model_name='booking_table',
            name='SCHEDULE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorBooking.schedule_table'),
        ),
        migrations.CreateModel(
            name='user_reg_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=20)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=20)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorBooking.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_rating_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorBooking.doctor_reg_table')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorBooking.user_reg_table')),
            ],
        ),
        migrations.AddField(
            model_name='booking_table',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DoctorBooking.user_reg_table'),
        ),
    ]
